import { useCallback, useEffect, useState } from "react";
import { api, ApiError } from "../api/client";
import type { PredictResponse } from "../api/types";
import { useAuth } from "../auth/AuthContext";
import { Dropzone } from "../components/Dropzone";
import { FaceBoxes } from "../components/FaceBoxes";
import { ResultCard } from "../components/ResultCard";
import { Disclaimer, ErrorAlert, Panel, Spinner } from "../components/ui";

export function AnalyzePage() {
  const { token, user } = useAuth();
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [result, setResult] = useState<PredictResponse | null>(null);
  const [error, setError] = useState<ApiError | string | null>(null);
  const [busy, setBusy] = useState(false);
  const [store, setStore] = useState(false);
  const [selected, setSelected] = useState(0);

  useEffect(() => {
    if (!file) return;
    const url = URL.createObjectURL(file);
    setPreview(url);
    return () => URL.revokeObjectURL(url); // free memory; the image never leaves the browser except to the API
  }, [file]);

  const analyze = useCallback(
    async (next: File) => {
      setFile(next);
      setResult(null);
      setError(null);
      setSelected(0);
      setBusy(true);
      try {
        setResult(await api.predict(next, { store: store && !!user, explain: true }, token));
      } catch (err) {
        setError(err instanceof ApiError ? err : String(err));
      } finally {
        setBusy(false);
      }
    },
    [store, token, user],
  );

  const reset = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
    setError(null);
  };

  const selectFace = (index: number) => {
    setSelected(index);
    document.getElementById(`face-${index}`)?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight text-white">Is this face real or AI-generated?</h1>
        <p className="max-w-2xl text-slate-400">
          Upload a photo. DeepTrace finds each face, estimates the probability it was generated by AI, and shows a
          heatmap of the regions that drove its decision.
        </p>
      </div>
      <Disclaimer />

      {!file && (
        <Panel className="space-y-4">
          <Dropzone onFile={analyze} onInvalid={(msg) => setError(msg)} disabled={busy} />
          <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-slate-400">
            <span>🔒 By default your photo is analysed in memory and deleted immediately — nothing is stored.</span>
            {user ? (
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={store} onChange={(e) => setStore(e.target.checked)} className="accent-accent" />
                Save this analysis to my history
              </label>
            ) : (
              <span className="text-slate-500">Log in on the History page to optionally save results.</span>
            )}
          </div>
          {error && <ErrorAlert error={error} />}
        </Panel>
      )}

      {file && preview && (
        <div className="grid gap-6 lg:grid-cols-[minmax(0,5fr)_minmax(0,6fr)]">
          <div className="space-y-4 lg:sticky lg:top-20 lg:self-start">
            <Panel className="space-y-3">
              {result ? (
                <FaceBoxes src={preview} width={result.image.width} height={result.image.height} faces={result.faces}
                  selected={selected} onSelect={selectFace} />
              ) : (
                <img src={preview} alt="Uploaded photo" className="w-full rounded-lg" />
              )}
              <div className="flex items-center justify-between gap-3">
                <span className="truncate text-xs text-slate-500">{file.name}</span>
                <button onClick={reset} className="rounded-md border border-line px-3 py-1.5 text-sm hover:border-slate-500">
                  Analyze another photo
                </button>
              </div>
            </Panel>
            {result && (
              <p className="text-xs text-slate-500">
                {result.faces.length} face{result.faces.length === 1 ? "" : "s"} · model {result.model.name} v
                {result.model.version} · {Object.values(result.timings_ms).reduce((a, b) => a + b, 0).toFixed(0)} ms ·{" "}
                {result.stored ? "saved to your history" : "not stored"}
              </p>
            )}
          </div>

          <div className="space-y-4">
            {busy && (
              <Panel>
                <Spinner label="Detecting faces and analysing…" />
              </Panel>
            )}
            {error && <ErrorAlert error={error} />}
            {result?.faces.map((face) => (
              <div key={face.face_index} id={`face-${face.face_index}`}
                className={`scroll-mt-24 rounded-xl ${face.face_index === selected && result.faces.length > 1 ? "ring-2 ring-accent/60" : ""}`}>
                <ResultCard face={face} model={result.model} total={result.faces.length} />
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
